language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test && npm run build
deploy:
  provider: s3
  access_key_id: AKIA2RVMN3PXYSXV4IFX
  secret_access_key:
    secure: mRHDLlNoe/sCdf8pvnPSgGJYAF3f2P5tsNWyYGsnPNpW+YN4ha7kMx++tFZ6f+rNdWOfWBVscyx9HtOa0v5g40HKeoqmUb3i4t+NH6lx/CllLOfaitAFrCsYXjX3p5NfghoYirNK67ZnX6u3hlhrWX3/u83paw6+zZTBscLbu8yomMP4npr5ieKjGWsHSB6qQnBWAprM9ekWOwbQmnK8lEyYpHLh2xhM/0w9wV5kvNgV2VLyCsxgEYpnzRptmWIRH2mPA+lDFXfPCq3BPHY22Jr7YKzMXo4GjsVXbAktoQJAkzi0LP9hSGmJT/h+AQwwd+18DbdBHhIxtO2lIZJoqXT0KOJ6aW8F9yHEkAo9HTDXmBt/WQCK0wxEGd7aoldTeJsN6njWVCbaUNdTzntCd4GOz9kmmexGTWItDoMZaWu55KJic7nHBlH7ucoWwB/V8Ou97iFwt4zec45D92QALXFZvcBDWUMSzRhDc7Q5BUHzA/jkEUsERtPelmPQVripL9dCFHXUqyei0V7FxfzP5kJAM+Y0PFmHoFpJ3YvrTf0bL4/6ahLyhKuf9P0UC4SKol57TyaCMhTVuX+DxrnSfr5ArJ0FeMSEC4s8le82T41V6clWwt+3cKrvLEFeU79Cs0WJDlbYL2+RhW6NxLaZJGEYGt4Yf1+F54mHnmaTXWU=
  bucket: diogodomene.tk
  acl: bucket_owner_full_control
  on:
    repo: domenester/react-initializer
  skip_cleanup: 'true'
  local_dir: build
